spring:
  application:
    name: semestr0v04ka3

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT}
      password: ${SPRING_REDIS_PASSWORD}
      repositories:
        enabled: false

minio:
  endpoint: ${MINIO_ENDPOINT:}
  root-password: ${MINIO_ROOT_USER};
  root-user: ${MINIO_ROOT_PASSWORD};
  bucket: ${MINIO_BUCKET}

problem-queue-workers:
  redisDequeueTimeoutSeconds: 5
  workers-count: 4

test-container:
  docker-file: ${TEST_CONTAINER_DOCKERFILE}
  script: ${TEST_CONTAINER_SCRIPT}

logging:
  level:
    com.technokratos.securitytest: DEBUG


services:
  solution-service:
    url: localhost:8080/api/v1/solution
  problem-service:
    url: localhost:8080/api/v1/problems
